// auto-generated by sim/engine.py export_web — do not edit by hand
window.TREE = {
  "nodes": [
    {
      "id": "organization:root",
      "type": "organization",
      "title": "The buyer organization (as modelled by the advisor)",
      "parent": "null",
      "provenance": "user-intent",
      "status": "approved",
      "approved_by": "ali",
      "proposed_by": "claude-web",
      "tags": [
        "root"
      ]
    },
    {
      "id": "faros:root",
      "type": "faros",
      "title": "Faros AI \u2014 offering root",
      "parent": "organization:root",
      "provenance": "sourced",
      "status": "approved",
      "approved_by": "ali",
      "proposed_by": "claude-web",
      "honesty": "shipped",
      "source": {
        "kind": "press-release",
        "quote_or_derivation": "Faros V observes AI work from tickets to outcomes to spend, optimizes context, governs with provenance."
      },
      "tags": [
        "faros",
        "offering"
      ]
    },
    {
      "id": "faros:govern",
      "type": "faros",
      "title": "Govern \u2014 policy, distributed context, provenance",
      "parent": "faros:root",
      "provenance": "sourced",
      "status": "approved",
      "approved_by": "ali",
      "proposed_by": "claude-web",
      "honesty": "roadmap",
      "source": {
        "kind": "press-release",
        "quote_or_derivation": "Policies set centrally; banned model or missing context shows up; audit trail from ticket to shipped change."
      },
      "fields": {
        "layer": "capability",
        "pillar": "govern"
      },
      "tags": [
        "faros",
        "govern",
        "partial"
      ]
    },
    {
      "id": "faros:observe",
      "type": "faros",
      "title": "Observe \u2014 the operational graph",
      "parent": "faros:root",
      "provenance": "sourced",
      "status": "approved",
      "approved_by": "ali",
      "proposed_by": "claude-web",
      "honesty": "shipped",
      "source": {
        "kind": "press-release",
        "quote_or_derivation": "Every AI token traced to the work it produced down to session, file, and decision, in a unified operational graph."
      },
      "fields": {
        "layer": "capability",
        "pillar": "observe"
      },
      "tags": [
        "faros",
        "observe",
        "shipped"
      ]
    },
    {
      "id": "faros:optimize",
      "type": "faros",
      "title": "Optimize \u2014 context that makes AI accurate",
      "parent": "faros:root",
      "provenance": "sourced",
      "status": "approved",
      "approved_by": "ali",
      "proposed_by": "claude-web",
      "honesty": "roadmap",
      "source": {
        "kind": "press-release",
        "quote_or_derivation": "Faros generates skills, rules, and tools tailored to each repo; recommends models per task."
      },
      "fields": {
        "layer": "capability",
        "pillar": "optimize"
      },
      "tags": [
        "faros",
        "optimize",
        "partial"
      ]
    },
    {
      "id": "flow:board-asks-roi",
      "type": "flow",
      "title": "Flow \u2014 board asks 'what did the AI spend buy?'",
      "parent": "organization:root",
      "provenance": "inferred",
      "status": "approved",
      "approved_by": "ali",
      "proposed_by": "claude-web",
      "fields": {
        "stage": "reporting",
        "actors": [
          "Maya",
          "board/CFO"
        ],
        "ai_touchpoints": [
          "token spend across Copilot/Cursor/Claude Code"
        ],
        "current_tools": [
          "FinOps/cost tool",
          "delivery dashboard",
          "last quarter's survey",
          "a spreadsheet"
        ]
      },
      "tags": [
        "flow",
        "roi",
        "reporting"
      ]
    },
    {
      "id": "flow:incident-to-cause",
      "type": "flow",
      "title": "Flow \u2014 from production incident to root cause",
      "parent": "organization:root",
      "provenance": "inferred",
      "status": "approved",
      "approved_by": "ali",
      "proposed_by": "claude-web",
      "fields": {
        "stage": "post-delivery",
        "actors": [
          "on-call",
          "staff engineer",
          "the AI agent that wrote the change"
        ],
        "ai_touchpoints": [
          "AI session generated the PR",
          "context the session did/didn't have"
        ],
        "current_tools": [
          "incident tool",
          "delivery dashboard",
          "cost tool",
          "catalog"
        ]
      },
      "tags": [
        "flow",
        "incident",
        "signature"
      ]
    },
    {
      "id": "mapping:maya-govern-velocity",
      "type": "mapping",
      "title": "Mapping \u2014 govern AI merges without slowing down \u2192 compensating controls",
      "parent": "organization:root",
      "provenance": "inferred",
      "status": "approved",
      "approved_by": "ali",
      "proposed_by": "claude-web",
      "honesty": "roadmap",
      "fields": {
        "persona_ref": "persona:maya",
        "flow_ref": "flow:incident-to-cause",
        "pain": "Need to govern AI merges and policy without killing velocity.",
        "faros_ref": "faros:govern",
        "evidence": "Instead of a hard block, require a compensating control \u2014 ship behind a feature flag. The change still ships today; blast radius contained, rollback instant; a human still reviews and merges."
      },
      "tags": [
        "mapping",
        "govern",
        "velocity",
        "guardrails",
        "roadmap"
      ]
    },
    {
      "id": "mapping:maya-incident-observe",
      "type": "mapping",
      "title": "Mapping \u2014 Maya's incident-to-cause pain \u2192 Observe",
      "parent": "organization:root",
      "provenance": "inferred",
      "status": "approved",
      "approved_by": "ali",
      "proposed_by": "claude-web",
      "honesty": "shipped",
      "fields": {
        "persona_ref": "persona:maya",
        "flow_ref": "flow:incident-to-cause",
        "pain": "When a P1 hits, the trail goes cold at every tool boundary; can't reach the session or the missing context that caused it.",
        "faros_ref": "faros:observe",
        "evidence": "Operational graph joins ticket\u2192session\u2192PR\u2192deploy\u2192incident\u2192spend; traces to the one missing repo rule."
      },
      "tags": [
        "mapping",
        "signature",
        "shipped"
      ]
    },
    {
      "id": "mapping:maya-learning-negmem",
      "type": "mapping",
      "title": "Mapping \u2014 Maya's repeat-mistakes pain \u2192 Negative Memory",
      "parent": "organization:root",
      "provenance": "inferred",
      "status": "approved",
      "approved_by": "ali",
      "proposed_by": "claude-web",
      "honesty": "roadmap",
      "fields": {
        "persona_ref": "persona:maya",
        "flow_ref": "flow:incident-to-cause",
        "pain": "Agents make the same mistake next week; lessons live in one senior's head, not the team's.",
        "faros_ref": "faros:govern",
        "evidence": "Replay the failed session, write the rule back into repo context so no agent (and no junior) repeats it."
      },
      "tags": [
        "mapping",
        "learning",
        "roadmap"
      ]
    },
    {
      "id": "mapping:maya-roi-ledger",
      "type": "mapping",
      "title": "Mapping \u2014 Maya's board-ROI pain \u2192 Token Attribution Ledger",
      "parent": "organization:root",
      "provenance": "sourced",
      "status": "approved",
      "approved_by": "ali",
      "proposed_by": "claude-web",
      "honesty": "shipped",
      "source": {
        "kind": "market-research",
        "quote_or_derivation": "Your AI vendors tell you what you spent; Faros tells you what it produced (Token Intelligence, Jun 2026)."
      },
      "fields": {
        "persona_ref": "persona:maya",
        "flow_ref": "flow:board-asks-roi",
        "pain": "Can't tell the board what the AI spend produced; four tools, zero joins.",
        "faros_ref": "faros:observe",
        "evidence": "Token Attribution Ledger ties every dollar to the work it did and the outcome it shipped; classifies productive/inefficient/wasteful."
      },
      "tags": [
        "mapping",
        "roi",
        "door",
        "shipped"
      ]
    },
    {
      "id": "mapping:maya-surveillance-govern",
      "type": "mapping",
      "title": "Mapping \u2014 'is this surveillance?' \u2192 repo/system-level governance",
      "parent": "organization:root",
      "provenance": "inferred",
      "status": "approved",
      "approved_by": "ali",
      "proposed_by": "claude-web",
      "honesty": "shipped",
      "fields": {
        "persona_ref": "persona:maya",
        "flow_ref": "flow:incident-to-cause",
        "pain": "Worried this becomes engineer surveillance \u2014 ranking, monitoring, individual keystroke tracking.",
        "faros_ref": "faros:govern",
        "evidence": "Everything lands at the repo/system level \u2014 context rules, feature flags, traces, policy \u2014 never individual keystrokes. A human still reviews and merges. Built to empower the team, not police it."
      },
      "tags": [
        "mapping",
        "surveillance",
        "empower",
        "govern",
        "shipped"
      ]
    },
    {
      "id": "mapping:maya-tool-rationalization",
      "type": "mapping",
      "title": "Mapping \u2014 which AI tools/models are worth keeping \u2192 Optimize",
      "parent": "organization:root",
      "provenance": "sourced",
      "status": "approved",
      "approved_by": "ali",
      "proposed_by": "claude-web",
      "honesty": "roadmap",
      "source": {
        "kind": "market-research",
        "quote_or_derivation": "Token Intelligence gives each tool a keep / scope / cut verdict; recommends models per task."
      },
      "fields": {
        "persona_ref": "persona:maya",
        "flow_ref": "flow:board-asks-roi",
        "pain": "Too many models and tools; which are worth keeping, which to cut or standardize on?",
        "faros_ref": "faros:optimize",
        "evidence": "Classifies tokens productive/inefficient/wasteful and gives each tool a keep/scope/cut verdict; recommends the right model per task type."
      },
      "tags": [
        "mapping",
        "optimize",
        "tools",
        "rationalization",
        "roadmap"
      ]
    },
    {
      "id": "persona:maya",
      "type": "persona",
      "title": "Maya \u2014 VP Platform Engineering (primary buyer)",
      "parent": "organization:root",
      "provenance": "inferred",
      "status": "approved",
      "approved_by": "ali",
      "proposed_by": "claude-web",
      "fields": {
        "role": "VP, Platform Engineering",
        "org_context": "~1,200 engineers, B2B SaaS, multi-tool AI shop (Copilot, Cursor, Claude Code), ~90% adoption, renewal coming",
        "pressures": [
          "board wants the AI line item justified in outcomes",
          "developers want help not surveillance",
          "throughput up but incidents and rework up too"
        ],
        "success_criteria": [
          "answer 'what did the spend buy?' with evidence",
          "trace an incident to root cause",
          "turn failures into memory",
          "govern without slowing down",
          "empower the team, never rank it"
        ]
      },
      "tags": [
        "persona",
        "buyer",
        "maya"
      ]
    },
    {
      "id": "principle:empower-not-police",
      "type": "principle",
      "title": "Principle \u2014 empower the team, never police it",
      "parent": "organization:root",
      "provenance": "user-intent",
      "status": "approved",
      "approved_by": "ali",
      "proposed_by": "claude-web",
      "fields": {
        "statement": "Measurement and governance land at the repo/system level \u2014 tools, context, policy \u2014 never individual keystrokes.",
        "why_it_matters": "It's the difference between a tool developers adopt and one they route around; it's also the honest design.",
        "risk_if_lost": "The product becomes a surveillance scoreboard, developers reject it, and the FinOps/cost-policing read wins."
      },
      "tags": [
        "principle",
        "culture",
        "surveillance"
      ]
    },
    {
      "id": "principle:transfer-of-mastery",
      "type": "principle",
      "title": "Principle \u2014 transfer of mastery (human + machine memory)",
      "parent": "organization:root",
      "provenance": "user-intent",
      "status": "approved",
      "approved_by": "ali",
      "proposed_by": "claude-web",
      "fields": {
        "statement": "A senior's hard-won lesson should become the team's standing knowledge \u2014 read by the next junior and by every agent.",
        "why_it_matters": "Closes the MIT learning gap: the system retains context and improves instead of repeating mistakes.",
        "risk_if_lost": "Transfer of learning gets buried in the AI world; seniors, juniors, and new hires all lose the structure that makes a strong team legendary."
      },
      "tags": [
        "principle",
        "culture",
        "learning",
        "climax"
      ]
    }
  ],
  "threshold": 0.3,
  "synonyms": {
    "incident": [
      "broke",
      "broken",
      "bug",
      "down",
      "failure",
      "incident",
      "outage",
      "p0",
      "p1",
      "production",
      "sev"
    ],
    "spend": [
      "bill",
      "budget",
      "cost",
      "dollar",
      "money",
      "roi",
      "spend",
      "wasted",
      "wasteful"
    ],
    "learn": [
      "again",
      "knowledge",
      "learn",
      "learned",
      "learning",
      "memory",
      "mistake",
      "remember",
      "repeat",
      "repeating"
    ],
    "surveil": [
      "individual",
      "keystroke",
      "monitor",
      "monitoring",
      "police",
      "policing",
      "rank",
      "ranking",
      "spy",
      "surveil",
      "surveillance",
      "track",
      "tracking",
      "watch"
    ],
    "outcome": [
      "delivered",
      "impact",
      "outcome",
      "produce",
      "produced",
      "quality",
      "ship",
      "shipped",
      "shipping",
      "value"
    ],
    "trace": [
      "attribute",
      "attribution",
      "cause",
      "caused",
      "root",
      "session",
      "trace",
      "traceable",
      "where",
      "which"
    ],
    "govern": [
      "block",
      "blocked",
      "control",
      "flag",
      "govern",
      "governance",
      "guardrail",
      "merge",
      "policy",
      "review",
      "slow",
      "slowing",
      "velocity"
    ],
    "tool": [
      "claude",
      "copilot",
      "cursor",
      "cut",
      "keep",
      "model",
      "scope",
      "standardize",
      "tool",
      "tooling",
      "worth"
    ]
  },
  "stopwords": [
    "a",
    "about",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "been",
    "being",
    "by",
    "can",
    "could",
    "did",
    "do",
    "does",
    "for",
    "from",
    "had",
    "has",
    "have",
    "help",
    "how",
    "i",
    "if",
    "in",
    "into",
    "is",
    "it",
    "just",
    "me",
    "my",
    "no",
    "not",
    "of",
    "on",
    "or",
    "our",
    "out",
    "should",
    "so",
    "that",
    "the",
    "them",
    "they",
    "this",
    "to",
    "us",
    "was",
    "we",
    "were",
    "what",
    "when",
    "which",
    "who",
    "why",
    "will",
    "with",
    "would",
    "yes",
    "you",
    "your"
  ],
  "banned_positioning": [
    "spend less",
    "cut cost",
    "cut costs",
    "reduce spend",
    "reduce cost",
    "lower the bill",
    "save money",
    "cost-cutting",
    "spend down",
    "rank engineers",
    "rank developers",
    "monitor keystrokes",
    "surveil"
  ],
  "open_intents": [
    {
      "id": "open:pricing",
      "triggers": [
        "charge",
        "license",
        "price",
        "priced",
        "pricing",
        "subscription"
      ],
      "title": "How Faros itself is priced (open commercial question)",
      "answer": "That's the one open commercial question \u2014 and the cleanest FinOps-vs-platform tell. The call I'd make: price on the platform/outcome layer (seats or a connected-org tier), not on tokens or a percentage of savings \u2014 because consumption/savings pricing structurally bends the product toward 'spend less' and collapses the positioning. Public anchor seen: about $29/contributor/month. The signal that would flip me: if pricing proves consumption- or savings-based and Finance owns the buy, the FinOps read wins.",
      "honesty": "inference",
      "cite": "open:pricing"
    }
  ]
};
